### ISSUE TITLE
 Error: Another navigator is already registered for this container.

### ISSUE THREAD

**Issue by bella0413** [bella0413/wit2021#6]
Error: Another navigator is already registered for this container. You likely have multiple navigators under a single "NavigationContainer" or "Screen". Make sure each navigator is under a separate "Screen" container. See https://reactnavigation.org/docs/nesting-navigators for a guide on nesting.

**Comment by bella0413** [comment]
https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state

**Comment by bella0413** [comment]
https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state

**Comment by 2785160718** [comment]
Have you solved the problem? I have also met it. Could you please communicate with me

**Comment by bella0413** [comment]
Yes, I have solved it.
If you read this link carefully(https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state) , you can solve the problem.
